openpa_courts = [
    "Kebun Baru CC",
    "Teck Ghee CC",
    "Yio Chu Kang CC",
    "Bedok CC",
    "Eunos CC",
    "Fengshan CC",
    "Kaki Bukit CC",
    "Kampong Kembangan CC",
    "Siglap CC",
    "Bidadari CC",
    "Bishan CC",
    "Marymount CC",
    "Potong Pasir CC",
    "Boon Lay CC",
    "Yuhua CC",
    "Bukit Batok CC",
    "Hong Kah North CC",
    "Henderson CC",
    "Kim Seng CC",
    "Leng Kee CC",
    "Radin Mas CC",
    "Telok Blangah CC",
    "Bukit Panjang CC",
    "Senja-Cashew CC",
    "Zhenghua CC",
    "Bukit Timah CC",
    "Hillview CC",
    "Chua Chu Kang CC",
    "Keat Hong CC",
    "Yew Tee CC",
    "Ayer Rajah CC",
    "Clementi CC",
    "West Coast CC",
    "Geylang Serai CC",
    "Kallang CC",
    "Kampong Kembangan CC",
    "Kolam Ayer CC",
    "Fernvale CC",
    "Hougang CC",
    "Paya Lebar Kovan CC",
    "Taman Jurong CC",
    "Gek Poh Ville CC",
    "Jurong Green CC",
    "Jurong Spring CC",
    "Nanyang CC",
    "Taman Jurong CC",
    "The Frontier CC",
    "Jalan Besar CC",
    "Kallang CC",
    "Kampong Glam CC",
    "Kolam Ayer CC",
    "Pek Kio CC",
    "Whampoa CC",
    "Joo Chiat CC",
    "Kim Seng CC",
    "Kreta Ayer CC",
    "Tanjong Pagar CC",
    "Tiong Bahru CC",
    "Tanjong Pagar Spottiswoode Park RC",
    "Pasir Ris East CC",
    "Pasir Ris Elias CC",
    "Bidadari CC",
    "Eunos CC",
    "MacPherson CC",
    "Buona Vista CC",
    "Queenstown CC",
    "Canberra CC",
    "Marsiling CC",
    "Sembawang CC",
    "Anchorvale CC",
    "Buangkok CC",
    "Braddell Heights CC",
    "Hwi Yoh CC",
    "Changi Simei CC",
    "Tampines Changkat CC",
    "Tampines East CC",
    "Tampines North CC",
    "Cairnhill CC",
    "Tanglin CC",
    "Potong Pasir CC",
    "Toa Payoh Central CC",
    "Toa Payoh East CC",
    "Toa Payoh South CC",
    "Toa Payoh West CC",
    "ACE The Place CC",
    "Marsiling CC",
    "Woodlands CC",
    "Woodlands Galaxy CC",
    "Nee Soon East CC",
    "Nee Soon South CC",
]
